export const technologies = {
  frontend: [
    {
      name: "Typescript",
      description: "More powerful JavaScript",
      icon: "/ts.png",
      color: "#3178C690",
      link: "https://www.typescriptlang.org/",
    },
    {
      name: "React",
      description: "JavaScript Library",
      icon: "/react.png",
      color: "#61DAFB90",
      link: "https://reactjs.org/",
    },
    {
      name: "Next.js",
      description: "React Framework",
      icon: "/nextjs.svg",
      color: "#313131",
      link: "https://nextjs.org/",
    },
    {
      name: "Tailwind CSS",
      description: "CSS Framework",
      icon: "/tailwind.png",
      color: "#3CC0F890",
      link: "https://tailwindcss.com/",
    },
    {
      name: "Figma",
      description: "Design Tool",
      icon: "/figma.png",
      color: "#FC736290",
      link: "https://www.figma.com/",
    },
    {
      name: "Zustand",
      description: "State Manager",
      icon: "/zustand.png",
      color: "#EA661890",
      link: "https://zustand.docs.pmnd.rs/",
    },
  ],
  backend: [
    {
      name: "Node.js",
      description: "JavaScript Runtime",
      icon: "/nodejs.png",
      color: "#539D4190",
      link: "https://nodejs.org/",
    },
    {
      name: "Express",
      description: "Node.js Framework",
      icon: "/expressjs.svg",
      color: "#313131",
      link: "https://expressjs.com/",
    },
    {
      name: "Nest.js",
      description: "Node.js Framework",
      icon: "/nestjs.svg",
      color: "#E0234D90",
      link: "https://nestjs.com/",
    },
    {
      name: "Jest",
      description: "Testing Framework",
      icon: "/jest.png",
      color: "#C83C1490",
      link: "https://jestjs.io/",
    },
    {
      name: "Go",
      description: "Programming Language",
      icon: "/go_logo.webp",
      color: "#05ACD690",
      link: "https://go.dev/",
    },
    {
      name: "Auth.js",
      description: "Authentication",
      icon: "/nextauth.png",
      color: "#19D6C890",
      link: "https://next-auth.js.org/",
    },
    {
      name: "GraphQL",
      description: "Query Language",
      icon: "/graphql.png",
      color: "#E335A990",
      link: "https://graphql.org/",
    },
    {
      name: "Python",
      description: "Programming Language",
      icon: "/python.webp",
      color: "#33678D90",
      link: "https://www.python.org/",
    },
    {
      name: "FastAPI",
      description: "Backend Framework",
      icon: "/fastapi.svg",
      color: "#04998B90",
      link: "https://fastapi.tiangolo.com/",
    },
  ],
  devops: [
    {
      name: "Docker",
      description: "Containerization",
      icon: "/docker.webp",
      color: "#089CEB90",
      link: "https://www.docker.com/",
    },
    {
      name: "Nginx",
      description: "Web Server",
      icon: "/nginx.svg",
      color: "#00963990",
      link: "https://www.nginx.com/",
    },
  ],
  mobile: [
    {
      name: "React Native",
      description: "Mobile Framework",
      icon: "/react.png",
      color: "#3E8397",
      link: "https://reactnative.dev/",
    },
    {
      name: "NativeWind",
      description: "Tailwind for React Native",
      icon: "/nativewind.svg",
      color: "#3E8397",
      link: "https://nativewind.dev/",
    },
    {
      name: "Expo",
      description: "React Native Framework",
      icon: "/expo.webp",
      color: "#ffffff",
      link: "https://expo.dev/",
    },
  ],
  databases: [
    {
      name: "PostgreSQL",
      icon: "/postgres.webp",
      color: "#31679190",
      link: "https://www.postgresql.org/",
    },
    {
      name: "SQLite",
      icon: "/sqlite.png",
      color: "#43A3DC90",
      link: "https://www.sqlite.org/",
    },
    {
      name: "MySQL",
      icon: "/mysql.png",
      color: "#01618C90",
      link: "https://www.mysql.com/",
    },
    {
      name: "MongoDB",
      icon: "/mongo.webp",
      color: "#4CA94090",
      link: "https://www.mongodb.com/",
    },
    {
      name: "Firebase",
      icon: "/firebase.svg",
      color: "#FCCA3F90",
      link: "https://firebase.google.com/",
    },
    {
      name: "Supabase",
      icon: "/supabase.png",
      color: "#3ECF8C90",
      link: "https://supabase.com/",
    },
    {
      name: "Redis",
      icon: "/redis.svg",
      color: "#C62F2C90",
      link: "https://redis.io/",
    },
  ],
};
